CREATE
OR ALTER
VIEW [request].[vw_Requests]
AS
SELECT Id,
       AppraisalNo,
       Status,
       Purpose,
       HasAppraisalBook,
       Priority,
       Channel,
       OccurConstInspec,
       LoanApplicationNo,
       LimitAmt,
       TotalSellingPrice,
       PrevAppraisalNo,
       PrevAppraisalValue,
       PrevAppraisalDate,
       HouseNo,
       RoomNo,
       FloorNo,
       LocationIdentifier,
       Moo,
       Soi,
       Road,
       SubDistrict,
       District,
       Province,
       Postcode,
       ContactPersonName,
       ContactPersonContactNo,
       ProjectCode,
       FeeType,
       FeeRemark,
       RequestorEmpId,
       RequestorName,
       RequestorEmail,
       RequestorContactNo,
       RequestorAo,
       RequestorBranch,
       RequestorBusinessUnit,
       RequestorDepartment,
       RequestorSection,
       RequestorCostCenter
FROM request.Requests [Requests]
JOIN request.RequestDetails [RequestDetails]
ON RequestDetails.RequestId = Requests.Id