// <auto-generated />
using System;
using Appraisal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Appraisal.Data.Migrations
{
    [DbContext(typeof(AppraisalDbContext))]
    [Migration("20250821091916_MigrationMachineDetailInfo")]
    partial class MigrationMachineDetailInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Appraisal")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appraisal.MachineAppraisalDetails.Models.MachineAppraisalAdditionalInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MachDetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprId")
                        .IsUnique();

                    b.ToTable("MachineAppraisalAdditionalInfos", "Appraisal");
                });

            modelBuilder.Entity("Appraisal.MachineAppraisalDetails.Models.MachineAppraisalDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MachineApprID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprId")
                        .IsUnique();

                    b.ToTable("MachineAppraisalDetails", "Appraisal");
                });

            modelBuilder.Entity("Appraisal.RequestAppraisals.Models.RequestAppraisal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ApprId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollateralId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appraisals", "Appraisal");
                });

            modelBuilder.Entity("Appraisal.MachineAppraisalDetails.Models.MachineAppraisalAdditionalInfo", b =>
                {
                    b.HasOne("Appraisal.RequestAppraisals.Models.RequestAppraisal", null)
                        .WithOne("MachineAppraisalAdditionalInfo")
                        .HasForeignKey("Appraisal.MachineAppraisalDetails.Models.MachineAppraisalAdditionalInfo", "ApprId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Appraisal.MachineAppraisalDetails.ValueObjects.MachineDetail", "MachineDetail", b1 =>
                        {
                            b1.Property<long>("MachineAppraisalAdditionalInfoId")
                                .HasColumnType("bigint");

                            b1.HasKey("MachineAppraisalAdditionalInfoId");

                            b1.ToTable("MachineAppraisalAdditionalInfos", "Appraisal");

                            b1.WithOwner()
                                .HasForeignKey("MachineAppraisalAdditionalInfoId");

                            b1.OwnsOne("Appraisal.MachineAppraisalDetails.ValueObjects.AtSurveyDate", "AtSurveyDate", b2 =>
                                {
                                    b2.Property<long>("MachineDetailMachineAppraisalAdditionalInfoId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ApprScrap")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("ApprScrap");

                                    b2.Property<string>("Exterior")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Exterior");

                                    b2.Property<int?>("Installed")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("Installed");

                                    b2.Property<string>("Maintenance")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Maintenance");

                                    b2.Property<bool?>("MarketDemand")
                                        .HasColumnType("bit")
                                        .HasColumnName("MarketDemand");

                                    b2.Property<string>("MarketDemandRemark")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("MarketDemandRemark");

                                    b2.Property<int?>("NoOfAppraise")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("NoOfAppraise");

                                    b2.Property<int?>("NotInstalled")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("NotInstalled");

                                    b2.Property<string>("Performance")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Performance");

                                    b2.HasKey("MachineDetailMachineAppraisalAdditionalInfoId");

                                    b2.ToTable("MachineAppraisalAdditionalInfos", "Appraisal");

                                    b2.WithOwner()
                                        .HasForeignKey("MachineDetailMachineAppraisalAdditionalInfoId");
                                });

                            b1.OwnsOne("Appraisal.MachineAppraisalDetails.ValueObjects.GeneralMachinery", "GeneralMachinery", b2 =>
                                {
                                    b2.Property<long>("MachineDetailMachineAppraisalAdditionalInfoId")
                                        .HasColumnType("bigint");

                                    b2.Property<int?>("ApprNo")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("ApprNo");

                                    b2.Property<string>("Industrial")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Industrial");

                                    b2.Property<int?>("SurveyNo")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("SurveyNo");

                                    b2.HasKey("MachineDetailMachineAppraisalAdditionalInfoId");

                                    b2.ToTable("MachineAppraisalAdditionalInfos", "Appraisal");

                                    b2.WithOwner()
                                        .HasForeignKey("MachineDetailMachineAppraisalAdditionalInfoId");
                                });

                            b1.OwnsOne("Appraisal.MachineAppraisalDetails.ValueObjects.RightsAndConditionsOfLegalRestrictions", "RightsAndConditionsOfLegalRestrictions", b2 =>
                                {
                                    b2.Property<long>("MachineDetailMachineAppraisalAdditionalInfoId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("MachineLocation")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("MachineLocation");

                                    b2.Property<string>("Obligation")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("Obligation");

                                    b2.Property<string>("Other")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("Other");

                                    b2.Property<string>("Owner")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Owner");

                                    b2.Property<string>("Proprietor")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Proprietor");

                                    b2.HasKey("MachineDetailMachineAppraisalAdditionalInfoId");

                                    b2.ToTable("MachineAppraisalAdditionalInfos", "Appraisal");

                                    b2.WithOwner()
                                        .HasForeignKey("MachineDetailMachineAppraisalAdditionalInfoId");
                                });

                            b1.Navigation("AtSurveyDate")
                                .IsRequired();

                            b1.Navigation("GeneralMachinery")
                                .IsRequired();

                            b1.Navigation("RightsAndConditionsOfLegalRestrictions")
                                .IsRequired();
                        });

                    b.OwnsOne("Appraisal.MachineAppraisalDetails.ValueObjects.PurposeAndLocationMachine", "PurposeAndLocationMachine", b1 =>
                        {
                            b1.Property<long>("MachineAppraisalAdditionalInfoId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ApprCollatPurpose")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ApprCollatPurpose");

                            b1.Property<string>("ApprCollatType")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ApprCollatType");

                            b1.Property<string>("ApprDate")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ApprDate");

                            b1.Property<string>("Assignment")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Assignment");

                            b1.HasKey("MachineAppraisalAdditionalInfoId");

                            b1.ToTable("MachineAppraisalAdditionalInfos", "Appraisal");

                            b1.WithOwner()
                                .HasForeignKey("MachineAppraisalAdditionalInfoId");
                        });

                    b.Navigation("MachineDetail")
                        .IsRequired();

                    b.Navigation("PurposeAndLocationMachine")
                        .IsRequired();
                });

            modelBuilder.Entity("Appraisal.MachineAppraisalDetails.Models.MachineAppraisalDetail", b =>
                {
                    b.HasOne("Appraisal.RequestAppraisals.Models.RequestAppraisal", null)
                        .WithOne("MachineAppraisalDetails")
                        .HasForeignKey("Appraisal.MachineAppraisalDetails.Models.MachineAppraisalDetail", "ApprId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Appraisal.Appraisal.Shared.ValueObjects.AppraisalDetail", "AppraisalDetail", b1 =>
                        {
                            b1.Property<long>("MachineAppraisalDetailId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AppraiserOpinion")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AppraiserOpinion");

                            b1.Property<bool?>("CanUse")
                                .HasColumnType("bit")
                                .HasColumnName("CanUse");

                            b1.Property<string>("ConditionUse")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ConditionUse");

                            b1.Property<string>("Location")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Location");

                            b1.Property<string>("Other")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Other");

                            b1.Property<string>("Part")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MachinePart");

                            b1.Property<string>("Remark")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Remark");

                            b1.Property<string>("UsePurpose")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("UsePurpose");

                            b1.HasKey("MachineAppraisalDetailId");

                            b1.ToTable("MachineAppraisalDetails", "Appraisal");

                            b1.WithOwner()
                                .HasForeignKey("MachineAppraisalDetailId");
                        });

                    b.Navigation("AppraisalDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Appraisal.RequestAppraisals.Models.RequestAppraisal", b =>
                {
                    b.Navigation("MachineAppraisalAdditionalInfo")
                        .IsRequired();

                    b.Navigation("MachineAppraisalDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
