// <auto-generated />
using System;
using Collateral.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collateral.Data.Migrations
{
    [DbContext(typeof(CollateralDbContext))]
    [Migration("20250815095520_Debug2")]
    partial class Debug2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("collateral")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Collateral.CollateralMachines.Models.CollateralMachine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MachineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChassisNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CollatId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollatId")
                        .IsUnique();

                    b.ToTable("CollateralMachines", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMachines.Models.MachineAppraisalAdditionalInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MachineAppraisalAdditionalInfos", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMachines.Models.MachineAppraisalDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprId")
                        .HasColumnType("bigint");

                    b.Property<long>("CollatId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollatId")
                        .IsUnique();

                    b.ToTable("MachineAppraisalDetails", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CollatType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("HostCollatID")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CollateralMasters", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralVehicles.Models.CollateralVehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VehicleName");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChassisNo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("ChassisNo");

                    b.Property<long>("CollatId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollatId")
                        .IsUnique();

                    b.ToTable("CollateralVehicles", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralVehicles.Models.VehicleAppraisalDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprId")
                        .HasColumnType("bigint");

                    b.Property<long>("CollatId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollatId")
                        .IsUnique();

                    b.ToTable("VehicleAppraisalDetails", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralVessels.Models.CollateralVessel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VesselName");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChassisNo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("ChassisNo");

                    b.Property<long>("CollatId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollatId")
                        .IsUnique();

                    b.ToTable("CollateralVessels", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralVessels.Models.VesselAppraisalDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApprId")
                        .HasColumnType("bigint");

                    b.Property<long>("CollatId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollatId")
                        .IsUnique();

                    b.ToTable("VesselAppraisalDetails", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMachines.Models.CollateralMachine", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("CollateralMachine")
                        .HasForeignKey("Collateral.CollateralMachines.Models.CollateralMachine", "CollatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.CollateralDetail", "CollateralMachineDetail", b1 =>
                        {
                            b1.Property<long>("CollateralMachineId")
                                .HasColumnType("bigint");

                            b1.Property<string>("CountryOfManufacture")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("CountryOfManufacture");

                            b1.Property<string>("EngineNo")
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("EngineNo");

                            b1.Property<DateTime?>("PurchaseDate")
                                .HasMaxLength(30)
                                .HasColumnType("datetime2")
                                .HasColumnName("PurchaseDate");

                            b1.Property<decimal?>("PurchasePrice")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("PurchasePrice");

                            b1.Property<string>("RegistrationNo")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("RegistrationNo");

                            b1.Property<int?>("YearOfManufacture")
                                .HasColumnType("int")
                                .HasColumnName("YearOfManufacture");

                            b1.HasKey("CollateralMachineId");

                            b1.ToTable("CollateralMachines", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CollateralMachineId");
                        });

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.CollateralProperty", "CollateralMachineProperty", b1 =>
                        {
                            b1.Property<long>("CollateralMachineId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Brand")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Brand");

                            b1.Property<string>("EnergyUse")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("EnergyUse");

                            b1.Property<string>("Model")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Model");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MachineName");

                            b1.HasKey("CollateralMachineId");

                            b1.ToTable("CollateralMachines", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CollateralMachineId");
                        });

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.CollateralSize", "CollateralMachineSize", b1 =>
                        {
                            b1.Property<long>("CollateralMachineId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Capacity")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Capacity");

                            b1.Property<decimal?>("Height")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("Height");

                            b1.Property<decimal?>("Length")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("Length");

                            b1.Property<decimal?>("Width")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("Width");

                            b1.HasKey("CollateralMachineId");

                            b1.ToTable("CollateralMachines", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CollateralMachineId");
                        });

                    b.Navigation("CollateralMachineDetail")
                        .IsRequired();

                    b.Navigation("CollateralMachineProperty")
                        .IsRequired();

                    b.Navigation("CollateralMachineSize")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMachines.Models.MachineAppraisalAdditionalInfo", b =>
                {
                    b.OwnsOne("Collateral.CollateralMachines.ValueObjects.MachineDetail", "MachineDetail", b1 =>
                        {
                            b1.Property<long>("MachineAppraisalAdditionalInfoId")
                                .HasColumnType("bigint");

                            b1.HasKey("MachineAppraisalAdditionalInfoId");

                            b1.ToTable("MachineAppraisalAdditionalInfos", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("MachineAppraisalAdditionalInfoId");

                            b1.OwnsOne("Collateral.CollateralMachines.ValueObjects.AtSurveyDate", "AtSurveyDate", b2 =>
                                {
                                    b2.Property<long>("MachineDetailMachineAppraisalAdditionalInfoId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ApprScrap")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("ApprScrap");

                                    b2.Property<string>("Exterior")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Exterior");

                                    b2.Property<int?>("Installed")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("Installed");

                                    b2.Property<string>("Maintenance")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Maintenance");

                                    b2.Property<bool?>("MarketDemand")
                                        .HasColumnType("bit")
                                        .HasColumnName("MarketDemand");

                                    b2.Property<string>("MarketDemandRemark")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("MarketDemandRemark");

                                    b2.Property<int?>("NoOfAppraise")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("NoOfAppraise");

                                    b2.Property<int?>("NotInstalled")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("NotInstalled");

                                    b2.Property<string>("Performance")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Performance");

                                    b2.HasKey("MachineDetailMachineAppraisalAdditionalInfoId");

                                    b2.ToTable("MachineAppraisalAdditionalInfos", "collateral");

                                    b2.WithOwner()
                                        .HasForeignKey("MachineDetailMachineAppraisalAdditionalInfoId");
                                });

                            b1.OwnsOne("Collateral.CollateralMachines.ValueObjects.GeneralMachinery", "GeneralMachinery", b2 =>
                                {
                                    b2.Property<long>("MachineDetailMachineAppraisalAdditionalInfoId")
                                        .HasColumnType("bigint");

                                    b2.Property<int?>("ApprNo")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("ApprNo");

                                    b2.Property<string>("Industrial")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Industrial");

                                    b2.Property<int?>("SurveyNo")
                                        .HasMaxLength(10)
                                        .HasColumnType("int")
                                        .HasColumnName("SurveyNo");

                                    b2.HasKey("MachineDetailMachineAppraisalAdditionalInfoId");

                                    b2.ToTable("MachineAppraisalAdditionalInfos", "collateral");

                                    b2.WithOwner()
                                        .HasForeignKey("MachineDetailMachineAppraisalAdditionalInfoId");
                                });

                            b1.OwnsOne("Collateral.CollateralMachines.ValueObjects.RightsAndConditionsOfLegalRestrictions", "RightsAndConditionsOfLegalRestrictions", b2 =>
                                {
                                    b2.Property<long>("MachineDetailMachineAppraisalAdditionalInfoId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("MachineLocation")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("MachineLocation");

                                    b2.Property<string>("Obligation")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("Obligation");

                                    b2.Property<string>("Other")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("Other");

                                    b2.Property<string>("Owner")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Owner");

                                    b2.Property<string>("Proprietor")
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("Proprietor");

                                    b2.HasKey("MachineDetailMachineAppraisalAdditionalInfoId");

                                    b2.ToTable("MachineAppraisalAdditionalInfos", "collateral");

                                    b2.WithOwner()
                                        .HasForeignKey("MachineDetailMachineAppraisalAdditionalInfoId");
                                });

                            b1.Navigation("AtSurveyDate")
                                .IsRequired();

                            b1.Navigation("GeneralMachinery")
                                .IsRequired();

                            b1.Navigation("RightsAndConditionsOfLegalRestrictions")
                                .IsRequired();
                        });

                    b.OwnsOne("Collateral.CollateralMachines.ValueObjects.PurposeAndLocationMachine", "PurposeAndLocationMachine", b1 =>
                        {
                            b1.Property<long>("MachineAppraisalAdditionalInfoId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ApprCollatPurpose")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ApprCollatPurpose");

                            b1.Property<string>("ApprCollatType")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ApprCollatType");

                            b1.Property<string>("ApprDate")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ApprDate");

                            b1.Property<string>("Assignment")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Assignment");

                            b1.HasKey("MachineAppraisalAdditionalInfoId");

                            b1.ToTable("MachineAppraisalAdditionalInfos", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("MachineAppraisalAdditionalInfoId");
                        });

                    b.Navigation("MachineDetail")
                        .IsRequired();

                    b.Navigation("PurposeAndLocationMachine")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMachines.Models.MachineAppraisalDetail", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("MachineAppraisalDetail")
                        .HasForeignKey("Collateral.CollateralMachines.Models.MachineAppraisalDetail", "CollatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.AppraisalDetail", "AppraisalDetail", b1 =>
                        {
                            b1.Property<long>("MachineAppraisalDetailId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AppraiserOpinion")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AppraiserOpinion");

                            b1.Property<bool?>("CanUse")
                                .HasColumnType("bit")
                                .HasColumnName("CanUse");

                            b1.Property<string>("ConditionUse")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ConditionUse");

                            b1.Property<string>("Location")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Location");

                            b1.Property<string>("Other")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Other");

                            b1.Property<string>("Part")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MachinePart");

                            b1.Property<string>("Remark")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Remark");

                            b1.Property<string>("UsePurpose")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("UsePurpose");

                            b1.HasKey("MachineAppraisalDetailId");

                            b1.ToTable("MachineAppraisalDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("MachineAppraisalDetailId");
                        });

                    b.Navigation("AppraisalDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralVehicles.Models.CollateralVehicle", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("CollateralVehicle")
                        .HasForeignKey("Collateral.CollateralVehicles.Models.CollateralVehicle", "CollatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.CollateralDetail", "CollateralVehicleDetail", b1 =>
                        {
                            b1.Property<long>("CollateralVehicleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("CountryOfManufacture")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("CountryOfManufacture");

                            b1.Property<string>("EngineNo")
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("EngineNo");

                            b1.Property<DateTime?>("PurchaseDate")
                                .HasMaxLength(30)
                                .HasColumnType("datetime2")
                                .HasColumnName("PurchaseDate");

                            b1.Property<decimal?>("PurchasePrice")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("PurchasePrice");

                            b1.Property<string>("RegistrationNo")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("RegistrationNo");

                            b1.Property<int?>("YearOfManufacture")
                                .HasColumnType("int")
                                .HasColumnName("YearOfManufacture");

                            b1.HasKey("CollateralVehicleId");

                            b1.ToTable("CollateralVehicles", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CollateralVehicleId");
                        });

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.CollateralProperty", "CollateralVehicleProperty", b1 =>
                        {
                            b1.Property<long>("CollateralVehicleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Brand")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Brand");

                            b1.Property<string>("EnergyUse")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("EnergyUse");

                            b1.Property<string>("Model")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Model");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MachineName");

                            b1.HasKey("CollateralVehicleId");

                            b1.ToTable("CollateralVehicles", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CollateralVehicleId");
                        });

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.CollateralSize", "CollateralVehicleSize", b1 =>
                        {
                            b1.Property<long>("CollateralVehicleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Capacity")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Capacity");

                            b1.Property<decimal?>("Height")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("Height");

                            b1.Property<decimal?>("Length")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("Length");

                            b1.Property<decimal?>("Width")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("Width");

                            b1.HasKey("CollateralVehicleId");

                            b1.ToTable("CollateralVehicles", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CollateralVehicleId");
                        });

                    b.Navigation("CollateralVehicleDetail")
                        .IsRequired();

                    b.Navigation("CollateralVehicleProperty")
                        .IsRequired();

                    b.Navigation("CollateralVehicleSize")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralVehicles.Models.VehicleAppraisalDetail", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("VehicleAppraisalDetail")
                        .HasForeignKey("Collateral.CollateralVehicles.Models.VehicleAppraisalDetail", "CollatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.AppraisalDetail", "AppraisalDetail", b1 =>
                        {
                            b1.Property<long>("VehicleAppraisalDetailId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AppraiserOpinion")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AppraiserOpinion");

                            b1.Property<bool?>("CanUse")
                                .HasColumnType("bit")
                                .HasColumnName("CanUse");

                            b1.Property<string>("ConditionUse")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ConditionUse");

                            b1.Property<string>("Location")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Location");

                            b1.Property<string>("Other")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Other");

                            b1.Property<string>("Part")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("VehiclePart");

                            b1.Property<string>("Remark")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Remark");

                            b1.Property<string>("UsePurpose")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("UsePurpose");

                            b1.HasKey("VehicleAppraisalDetailId");

                            b1.ToTable("VehicleAppraisalDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("VehicleAppraisalDetailId");
                        });

                    b.Navigation("AppraisalDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralVessels.Models.CollateralVessel", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("CollateralVessel")
                        .HasForeignKey("Collateral.CollateralVessels.Models.CollateralVessel", "CollatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.CollateralDetail", "CollateralVesselDetail", b1 =>
                        {
                            b1.Property<long>("CollateralVesselId")
                                .HasColumnType("bigint");

                            b1.Property<string>("CountryOfManufacture")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("CountryOfManufacture");

                            b1.Property<string>("EngineNo")
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("EngineNo");

                            b1.Property<DateTime?>("PurchaseDate")
                                .HasMaxLength(30)
                                .HasColumnType("datetime2")
                                .HasColumnName("PurchaseDate");

                            b1.Property<decimal?>("PurchasePrice")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("PurchasePrice");

                            b1.Property<string>("RegistrationNo")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("RegistrationNo");

                            b1.Property<int?>("YearOfManufacture")
                                .HasColumnType("int")
                                .HasColumnName("YearOfManufacture");

                            b1.HasKey("CollateralVesselId");

                            b1.ToTable("CollateralVessels", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CollateralVesselId");
                        });

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.CollateralProperty", "CollateralVesselProperty", b1 =>
                        {
                            b1.Property<long>("CollateralVesselId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Brand")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Brand");

                            b1.Property<string>("EnergyUse")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("EnergyUse");

                            b1.Property<string>("Model")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Model");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MachineName");

                            b1.HasKey("CollateralVesselId");

                            b1.ToTable("CollateralVessels", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CollateralVesselId");
                        });

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.CollateralSize", "CollateralVesselSize", b1 =>
                        {
                            b1.Property<long>("CollateralVesselId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Capacity")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Capacity");

                            b1.Property<decimal?>("Height")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("Height");

                            b1.Property<decimal?>("Length")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("Length");

                            b1.Property<decimal?>("Width")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("Width");

                            b1.HasKey("CollateralVesselId");

                            b1.ToTable("CollateralVessels", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CollateralVesselId");
                        });

                    b.Navigation("CollateralVesselDetail")
                        .IsRequired();

                    b.Navigation("CollateralVesselProperty")
                        .IsRequired();

                    b.Navigation("CollateralVesselSize")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralVessels.Models.VesselAppraisalDetail", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("VesselAppraisalDetail")
                        .HasForeignKey("Collateral.CollateralVessels.Models.VesselAppraisalDetail", "CollatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.Collateral.Shared.ValueObjects.AppraisalDetail", "AppraisalDetail", b1 =>
                        {
                            b1.Property<long>("VesselAppraisalDetailId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AppraiserOpinion")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AppraiserOpinion");

                            b1.Property<bool?>("CanUse")
                                .HasColumnType("bit")
                                .HasColumnName("CanUse");

                            b1.Property<string>("ConditionUse")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ConditionUse");

                            b1.Property<string>("Location")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Location");

                            b1.Property<string>("Other")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Other");

                            b1.Property<string>("Part")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("VesselPart");

                            b1.Property<string>("Remark")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Remark");

                            b1.Property<string>("UsePurpose")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("UsePurpose");

                            b1.HasKey("VesselAppraisalDetailId");

                            b1.ToTable("VesselAppraisalDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("VesselAppraisalDetailId");
                        });

                    b.Navigation("AppraisalDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralMaster", b =>
                {
                    b.Navigation("CollateralMachine")
                        .IsRequired();

                    b.Navigation("CollateralVehicle")
                        .IsRequired();

                    b.Navigation("CollateralVessel")
                        .IsRequired();

                    b.Navigation("MachineAppraisalDetail")
                        .IsRequired();

                    b.Navigation("VehicleAppraisalDetail")
                        .IsRequired();

                    b.Navigation("VesselAppraisalDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
