// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Request.Data;

#nullable disable

namespace Request.Data.Migrations
{
    [DbContext(typeof(RequestDbContext))]
    [Migration("20250623042254_InitialByMe1")]
    partial class InitialByMe1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("request")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Request.Requests.Models.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RequestId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppraisalNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Requests", "request");
                });

            modelBuilder.Entity("Request.Requests.Models.Request", b =>
                {
                    b.OwnsMany("Request.Requests.ValueObjects.RequestCustomer", "Customers", b1 =>
                        {
                            b1.Property<long>("CustomerId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("CustomerId"));

                            b1.Property<string>("ContactNo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar")
                                .HasColumnName("ContactNumber");

                            b1.Property<string>("CustName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("Name");

                            b1.Property<long>("RequestId")
                                .HasColumnType("bigint");

                            b1.HasKey("CustomerId");

                            b1.HasIndex("RequestId");

                            b1.ToTable("RequestCustomers", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Request.Requests.ValueObjects.RequestDetail", "Detail", b1 =>
                        {
                            b1.Property<long>("RequestId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Channel");

                            b1.Property<bool>("HasAppraisalBook")
                                .HasColumnType("bit")
                                .HasColumnName("HasAppraisalBook");

                            b1.Property<decimal?>("LimitAmt")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("LimitAmt");

                            b1.Property<string>("LoanApplicationNo")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("LoanApplicationNo");

                            b1.Property<int?>("OccurConstInspec")
                                .HasColumnType("int")
                                .HasColumnName("OccurConstInspec");

                            b1.Property<string>("Priority")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Priority");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Purpose");

                            b1.Property<decimal?>("TotalSellingPrice")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TotalSellingPrice");

                            b1.HasKey("RequestId");

                            b1.ToTable("RequestDetails", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");

                            b1.OwnsOne("Request.Requests.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<long>("RequestDetailRequestId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("District")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("District");

                                    b2.Property<string>("FloorNo")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("FloorNo");

                                    b2.Property<string>("HouseNo")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("HouseNo");

                                    b2.Property<string>("LocationIdentifier")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("LocationIdentifier");

                                    b2.Property<string>("Moo")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Moo");

                                    b2.Property<string>("Postcode")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("Postcode");

                                    b2.Property<string>("Province")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("Province");

                                    b2.Property<string>("Road")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Road");

                                    b2.Property<string>("RoomNo")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("RoomNo");

                                    b2.Property<string>("Soi")
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("Soi");

                                    b2.Property<string>("SubDistrict")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("SubDistrict");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Requests.ValueObjects.Fee", "Fee", b2 =>
                                {
                                    b2.Property<long>("RequestDetailRequestId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("FeeRemark")
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("FeeRemark");

                                    b2.Property<string>("FeeType")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("FeeType");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Requests.ValueObjects.Reference", "Reference", b2 =>
                                {
                                    b2.Property<long>("RequestDetailRequestId")
                                        .HasColumnType("bigint");

                                    b2.Property<DateTime?>("PrevAppraisalDate")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("PrevAppraisalDate");

                                    b2.Property<string>("PrevAppraisalNo")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("PrevAppraisalNo");

                                    b2.Property<decimal?>("PrevAppraisalValue")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("PrevAppraisalValue");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Requests.ValueObjects.Requestor", "Requestor", b2 =>
                                {
                                    b2.Property<long>("RequestDetailRequestId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("RequestorAo")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("RequestorAo");

                                    b2.Property<string>("RequestorBranch")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("RequestorBranch");

                                    b2.Property<string>("RequestorBusinessUnit")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("RequestorBusinessUnit");

                                    b2.Property<string>("RequestorContactNo")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("RequestorContactNo");

                                    b2.Property<string>("RequestorCostCenter")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("RequestorCostCenter");

                                    b2.Property<string>("RequestorDepartment")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("RequestorDepartment");

                                    b2.Property<string>("RequestorEmail")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("RequestorEmail");

                                    b2.Property<string>("RequestorEmpId")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("RequestorEmpId");

                                    b2.Property<string>("RequestorName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("RequestorName");

                                    b2.Property<string>("RequestorSection")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("RequestorSection");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("Fee")
                                .IsRequired();

                            b1.Navigation("Reference")
                                .IsRequired();

                            b1.Navigation("Requestor")
                                .IsRequired();
                        });

                    b.OwnsMany("Request.Requests.ValueObjects.RequestProperty", "Property", b1 =>
                        {
                            b1.Property<long>("PropertyId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("PropertyId"));

                            b1.Property<string>("BuildingType")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar")
                                .HasColumnName("BuildingType");

                            b1.Property<string>("PropertyType")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar")
                                .HasColumnName("PropertyType");

                            b1.Property<long>("RequestId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("SellingPrice")
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("SellingPrice");

                            b1.HasKey("PropertyId");

                            b1.HasIndex("RequestId");

                            b1.ToTable("RequestProperties", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.Navigation("Customers");

                    b.Navigation("Detail")
                        .IsRequired();

                    b.Navigation("Property");
                });
#pragma warning restore 612, 618
        }
    }
}
